exclude: '^\.git/|.*\.md$|.*\.txt$|.*\.json$|.*\.xml$'
repos:
  # Basic pre-commit checks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0  # 🚀 Use the latest stable version
    hooks:
      - id: trailing-whitespace
        name: 'Trim Trailing Whitespace 🧹'
      - id: check-merge-conflict
        name: 'Check for Merge Conflicts 🚩'
      - id: mixed-line-ending
        name: 'Fix Mixed Line Ending 🔄'
      - id: end-of-file-fixer
        name: 'Fix End of Files 📝'

    # Autoflake - Remove Unused Imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: 'Autoflake (Remove Unused Imports) 🧹'
        args: [--remove-all-unused-imports, --in-place]

  # Black - Code Formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0  # 🎨 Specify the version of Black you want to use
    hooks:
      - id: black
        name: 'Black (Code Formatter) 🖤'
        language_version: python3.10  # Specify the Python version

  # isort - Sorting Imports
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.12.0  # 📚 Use the latest stable version
    hooks:
      - id: isort
        name: 'isort (Imports Sorter) 🗂'
        args: ['--profile', 'black']

  # MyPy - Static Type Checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # 🔍 Use the latest version of MyPy
    hooks:
      - id: mypy
        name: 'MyPy (Type Checker) 🔎'
        additional_dependencies: [types-requests]  # Add additional dependencies if needed
