exclude: '^\.git/|.*\.md$|.*\.txt$|.*\.json$|.*\.xml$'
repos:
  # Basic pre-commit checks
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer

  # Remove unused Python imports
  - repo: 'https://github.com/myint/autoflake'
    rev: v2.1.1  # Use the latest stable version
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

  # Sort Python imports
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.12.0  # Use the latest stable version
    hooks:
      - id: isort
        args: ['--profile', 'black']

  # Black, but with a comparison to the current state
  - repo: 'https://github.com/akaihola/darker'
    rev: 1.7.1  # Use the latest stable version
    hooks:
      - id: darker

   # MyPy - Static Type Checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the latest version of MyPy
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]  # Add additional dependencies if needed
